experiment_name: 'Trophozoite_and_WBC_Run'
data:
  path: '/kaggle/input/datasets/sethkyei/malaria-mini-dataset/data/trophozoite-wbc'
model:
  num_classes: 3
  pre_trained: false
hyperparameters:
  batch_size: 2
  lr: 0.005
  num_workers: 2
  pin_memory: False
  num_epochs: 5


