experiment_name: 'Trophozoite_and_WBC_Run'
data:
  path: 'data/trophozoite-wbc'
model:
  num_classes: 3
  pre_trained: False
hyperparameters:
  batch_size: 4
  lr: 0.005
  num_workers: 4
  pin_memory: True
  num_epochs: 5
checkpoints:
  path: '/checkpoints/'
  name: 'retina_twbc_best_model'
